[project]
name = "mmmarkdown"
version = "0.1.0"
description = "MMMarkDown - Mindmap Markdown Editor"
requires-python = ">=3.12"
dependencies = [
    "pillow>=12.1.0",
    "pystray>=0.19.5",
]

[project.scripts]
mmm = "mmm_app:main"
